apiVersion: apps/v1
kind: Deployment
metadata:
  name: watson-media-e-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watson-media-e-learning
  template:
    metadata:
      labels:
        app: watson-media-e-learning
    spec:
      containers:
      - name: watson-media-e-learning
        image: randomUser/watson-node-elearning:v2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: watson-media-e-learning
  labels:
    app: watson-media-e-learning
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32423
  selector:
    app: watson-media-e-learning